im.riot.Riot.appdata.xml
im.riot.Riot.desktop
im.riot.Riot.json

fix #5 by using all the icons the app ships in /usr.
Fixes a validation error in the desktop file by adding a trailing semicolon
Adds OARS and a longer better description to the appdata

All icon sizes, more comprehensive appdata, desktop fix

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

Security fix, see
https://matrix.org/blog/2018/02/09/security-update-riotweb-0-13-5-released-fixing-xss-vulnerability/
Signed-off-by: Nicholas Sielicki <sielicki@yandex.com>

Update to 0.13.5

---

im.riot.Riot.appdata.xml

Since Riot 1.0 there is a redesign of Riot, that should be represented
in its screenshots.
This patch replaces the old screenshots with new ones from the 1.0 blog
post.
Fixes #35

Add new screenshots from 1.0 blog post

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

There was a hotfix released today: https://github.com/vector-im/riot-web/releases/tag/v1.0.5

 Update to Riot version 1.0.5 

---

im.riot.Riot.json

This is required for Fcitx users for characters such as backtick.
Ref: flatpak/flatpak#2031

add --talk-name=org.freedesktop.portal.Fcitx

---

im.riot.Riot.json

This permission is used by KDE as well as some Gnome extension to
provide tray icons and app indicators. In case of Riot it's required to
provide the Tray icon on Ubuntu.
Fixes #54

Add org.kde.StatusNotifierWatcher permission

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

This upgrade also contains a temporary disabling of the electron
sandbox. Since we don't ship SUID binaries in flatpaks and neasted user
namespaces are still not a thing, this is the only way to have electron
5 applications running within flatpak.
As soon as the flatpak upstream found a better solution, we'll switch to
it and remove the `--no-sandbox` option again.
Reference: https://github.com/flatpak/flatpak/issues/3044

Upgrade to version 1.3.5

---

im.riot.Riot.json

In order to keep our software up-to-date, lets switch the runtime
version to the latest and greatest 19.08.
Fixes #63

Switch runtime to 19.04

---

im.riot.Riot.json

Mixing different runtime and baseapp versions may accidentally work but in general it's not recommended.

Use 19.08 baseapp version

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

There is also 1.5.2, but it appears macOS specific and I didn't see a .deb for it.

Upgrade to version 1.5.1

---

im.riot.Riot.json

Also use non-persistent TMPDIR path as original /tmp would be.

Use zypak-wrapper instead of disabling sandbox

---

im.riot.Riot.json

The deb contains same content in  `/opt/Riot/resources/webapp` which is copied to `/Riot/resources/webapp` so github sources are just unnecessary duplicates.

Remove redundant source

---

im.riot.Riot.desktop

This allows Riot to work with SSO sign in so the homeserver can
redirect the user back to the Riot application after they have
logged in.
This was added recently to be compatible with the new SSO login flows.
Note that there are a few other fields missing from the flatpak's desktop file, I don't know if this is intentional. The full desktop file (generated by electron-builder) is:
```
[Desktop Entry]
Name=Riot
Exec=/opt/Riot/riot-web %U
Terminal=false
Type=Application
Icon=riot-web
StartupWMClass=riot
Comment=A feature-rich client for Matrix.org
MimeType=x-scheme-handler/riot;
Categories=Network;InstantMessaging;Chat;
```
This is also included in the deb file if it's easier to use that, patching as necessary.

Add riot:// scheme handler

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

Upgrading to the new release 1.6.0 with all needed dependency changes to use the new riot-desktop package, build the required dependencies and offer full-featured cross-signing with search indexing etc.

Upgrade to Riot-desktop 1.6.0

---

im.riot.Riot.json

~~According to riot sources they link to [sqlcipher statically](https://github.com/vector-im/riot-desktop/blob/bcb0611ee3504efe4e0054504214cd8c11ea7d1b/hak/matrix-seshat/build.js#L46) so we don't have to provide sqlcipher in flapak at all. I checked that nothing in riot binaries dynamically links to sqlcipher or tcl.~~
Tcl is only build dep and can be  cleaned out completely. Also clean other stuff like static libs which add significant amount of size and are unnecessary.

Cleanup new dependencies

---

im.riot.Riot.json

For the tray icon in KDE it's required to own the dbus of a naming
schema following `org.kde.KStatusNotifier-x-y`, where x is the
application's PID and y is an application's unique identifier. [1]
This change might introduces conflicts with other flatpaks that also try
to own this dbus name. If that happens, the tray icon might still won't
work. This should be kept in mind with this change. It's also
noteworthy, that this might breaks on any update and therefore should be
tested by people.
This entire change is required due to electron dropping `xembed`
support and Riot was upgrading Electron with 1.6.0.[2] If you are using
GNOME with tray icons there is a GNOME extension to help.[3]
An alternative implementation could have added `--own-name=org.kde.*`,
like the Zoom flatpak does for …

Add KDE notification dbus ownership

---

im.riot.Riot.appdata.xml
im.riot.Riot.desktop
im.riot.Riot.json

Riot was renamed to Element by the upstream project and recieved an
update to version 1.7.0 as part of the rebranding. With some discussions
in the project there is the expectation to **not** change the
application ID of the flatpak just because the application was
renamed. Therefore this patch only updates the visible indicators
but keeps the app-ID identical.
This patch renames all visible indicators from Riot to Element, upgrades
Element to version 1.7.0 and fixes the build system were needed.
Otherwise the flatpak itself stays the same, we still repackage the
upstream `.deb` as well as using the `im.riot.Riot` app-ID.
https://element.io/blog/welcome-to-element/
https://github.com/flathub/im.riot.Riot/issues/114

Rebrand Riot to Element

---

im.riot.Riot.desktop

This patch adds the window startup class to the desktop file to make
sure things are grouped properly.
Fixes #121

Add Window Startup class

---

im.riot.Riot.desktop

This patch fixes the previous change of the `StartUpWMClass` that we
introduced two commits ago. To fix the messed up windows pinning. Now we
change it again, as upstream decided to change the window name again.

Fix window class name for 1.7.2

---

.gitmodules
im.riot.Riot.json

It seems like encrypted search needs libsecret now. This patch provides
libsecret and should fix the problem therefore. It also removes the
unneeded permission for `org.freedesktop.secrets` as that's now handled
by libsecret and (if I recall correct) a portal.
Fixes #123

Fix broken search for encrypted messages

---

im.riot.Riot.json

This patch will force electron to use the gtk portal as file-picker. This
allows us to drop all directory access for the app without losing access
to file. This will fix drag-drop support as well as saving and uploading
files in Riot without requiring any special permissions.
Thanks a lot @refi64 for implementing this feature into the zypak!
Fixes #33

Upgrade runtime 20.08 and enable file-picker support in zypak

---

im.riot.Riot.appdata.xml
im.riot.Riot.json

As of Element 1.7.25, Electron 12 is used which enables people to start it with `--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland` and try out full Wayland support

Element 1.7.25 and Wayland support

---

im.riot.Riot.json

Old flatpak versions don't provide the `FLATPAK_ID` environment
variable. Therefore the script we use to start Riot fails to use correct
temporary directory which results in duplicated Riot instances trying to
run on the same configuration, which ultimately fails.
This patch fixes the whole problem by providing a fallback default which
should match.
Fixes #116

Fix compatiblity with old flatpak versions

---

im.riot.Riot.appdata.xml

While the spec officially supports `<em>` and `<code>`-tags, the
libraries used by the flathub frontend as well as GNOME software, don't
support these tags and just strip them, resulting in a non-functional
description for the flatpak on multiple platforms. While the right way
to do it, would be to fix to be applied to the upstream version of the
appstream-glib library, this doesn't seem to happen any time soon.
Therefore this patch removes the usage of the `<code>` and replaces it
with supported `<p>` tags, which might result in broken syntax if the
fonts substitute characters. That's nothing we can change.
References:
https://github.com/guinux/appstream-glib/commit/7fef9b4e0f2bbb33bd0f036413f3523ca5e821b8
https://github.com/flathub/linux-store-frontend/issues/203
Partly resolves issue …

Fix code tags in desktop metadata

---

im.riot.Riot.desktop

I borrowed all of these from org.gnome.Fractal.desktop, then added
'vector' to the untranslated key. (Before it was called Riot, Element
was called Vector.)
Fixes #138

Add keywords to desktop file

---

im.riot.Riot.appdata.xml

I figure adding these can't hurt?
I don't know if Flathub actually uses either of these `<url/>` types, but they're [part of the AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url).

Add help and translation URLs

---

im.riot.Riot.yaml

This patch updates the way TCL sources are handled by this flatpak. It drops the usage of the archive type in favour of the github mirror of TCL and upgrades TCL itself to version 8.6.11.

Rework TCL handling

---

im.riot.Riot.metainfo.xml
im.riot.Riot.yaml

This makes most sense to merge once Element does a new release, this isn't urgent or anything, just cleanup.
-Don't need PipeWire 0.2.7 module since Element builds against Electron 13, which supports PipeWire 0.3
-PipeWire 0.3 is included in the runtime.
-Mentioning the flag in the metainfo descrption will be redundant as of the next Element release (>1.8.1), see https://github.com/vector-im/element-web/issues/18607

Remove PipeWire module and metainfo mention

---

im.riot.Riot.metainfo.xml

This should be merged next update.
By default if the user starts the app normally the PipeWire capturer flag is passed (https://github.com/vector-im/element-desktop/pull/256).
However since Chromium only can use one instance of `--enable-features`, this will break usage of custom `--enable-features` flags from the user. This means the flags for Wayland won't work. This is the state of things as of 1.8.4.
So it was changed upstream https://github.com/vector-im/element-desktop/pull/261/commits/96e5389779f60c91b8fe80d7bd9af413d72ec61f if the user passed their own enable-features flags the upstream setting of the PipeWire flag is ignored, so now that means users need to make sure to pass the PipeWire flag along with the Ozone ones if they want native Wayland. This upstream change should make …

Re-add PipeWire capturer to flags in desktop file

---

im.riot.Riot.yaml

Update to latest and greatest Freedesktop 21.08 runtime. Tested this build locally and LGTM so far.

chore(update): org.freedesktop.Platform 21.08

---

im.riot.Riot.yaml

This patch removes the keyring mount since it's no longer required
thanks to portals for libsecret.
References:
https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Secret

fix(permissions): Remove unused keyring mount

---

im.riot.Riot.yaml

Partially fixes #33 and #68
Following the discussions on #33 I can see why we can't allow access to the entire user's home so this would at least help by allowing read-only access to more common directories.

Allow access to common xdg directories

---

im.riot.Riot.yaml

This patch removes all filesystem permssions since Electron now picks up
on portals. This will remove the need for such exposure.

feat(permissions): Remove unneeded permissions

---

im.riot.Riot.yaml

This patch drops support for any flatpak version prior to 1.7.0. This is
done to reduce potential overhead regarding old versions of Flatpak.
Instead of failing in hard to understand way, it'll fail to install with
a version provided by the flatpak command.
This will affect versions of Ubuntu and other distros that don't bother
to keep up with current flatpak development.
Be aware that flatpak 1.7.0 is 2 years old.
References:
https://matrix.to/#/!RfXaBjokqHAbzZrgHz:matrix.org/$JUBHbW6cUN6HtZJWdeinQQVHkoi1fnFH4hYuRdSaZcI?via=matrix.org&via=gnome.org&via=kde.org

fix: Wrong portal versions on too old flatpak

---

im.riot.Riot.yaml

This patch fixes the KDE tray icon support removed in the previous commit by implementing the general recommendation. This will not trigger the flatpak linter and make tray icons work reliably on KDE since it's no longer depending on the exact PID.
References:
https://github.com/flathub/im.riot.Riot/pull/306
https://matrix.to/#/!RfXaBjokqHAbzZrgHz:matrix.org/$gPmHj1ANaVEWBMKx5WbjIU6M86gQ86IC6UE-emQaehQ?via=matrix.org&via=gnome.org&via=kde.org

fix: Re-add the tray icon support on KDE

---

element.sh

It cannot be relied on $XDG_SESSION_TYPE alone, so verify the $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY socket exists.
Fixes the issue raised in https://github.com/flathub/im.riot.Riot/commit/2061305f3a847399d070b430acc8d4e906c88641#commitcomment-101202103

element.sh: Ensure in condition that Wayland socket exists

---

element.sh

This patch intentionally breaks search and can be used to disable the Element Search indexing for users unable to navigate to the right settings page on time.
This is achieved by replacing the existing search index directory (`${XDG_CONFIG_HOME}/<Element Profile>/EventStore`) with a file, triggering EEXIST error and resulting in a failed initialisation. This can easily be fixed using the UI and as long as all messages are still available on the homeserver, no data is lost and the index can be rebuilt.
In order to use this workaround, either start the flatpak using `flatpak run --env=DISABLE_ENCRYPTED_SEARCH=true im.riot.Riot` or add the environment variable using flatseal. A one time treatment should be enough as long as you already have a profile with an EventStore directory.

fix: Add workaround to disable broken search

---

element.sh

Chromium supports text-input-v1 under ozone wayland but requires the flag `--enable-wayland-ime` to enable it. KWin added support for this in https://invent.kde.org/plasma/kwin/-/merge_requests/3403 and Hyprland just landed support for this in https://github.com/hyprwm/Hyprland/pull/1778 as well.

Enable text-input-v1 support for Wayland IME under KWin/Weston/Hyprland

---

element.sh

Reverts flathub/im.riot.Riot#350
1.11.30 will probably be using electron24 which is based on chromium 112 which [crashes](https://bugs.chromium.org/p/chromium/issues/detail?id=1431532) with this flag.
Chromium has decided to break this so there's nothing much I can do...
Please merge when updating to 1.11.30

Revert "Enable text-input-v1 support for Wayland IME under KWin/Weston/Hyprland"

---

element.sh
im.riot.Riot.yaml

~~It's unfortunately still crashing when using seshat for search in encrypted rooms :(
Next version of seshat should allow to build openssl statically too, let's see if it helps.~~
Search in encrypted rooms has been fixed !

Use static build instead of unpacking the deb

---

im.riot.Riot.yaml

Element 1.11.36 uses Electron 25.0.0 based on Chromium 114.0.5735.45 which includes the patch https://chromium.googlesource.com/chromium/src/+/9585757f9fad5af3b3a0c113b4aebd0101fe1abc
It no longer requires ownership access
The patch is included in Electron >=23
In my testing `org.kde.StatusNotifierWatcher` also seems to be not required any more. But please test it on KDE and GNOME.

Drop `own-name=org.kde.*`

---

README.md

The previous link no longer works. This PR links it to the blog post announcing the change instead.

README: change URL for Riot name change info

---

im.riot.Riot.yaml

A new version of the runtime was recently released, see [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-23.08.0). Brings some updated packages, but they probably won't affect Element.

Use newer freedesktop platform 23.08

---

element.sh

Reverts flathub/im.riot.Riot#359
The actual bug has been fixed w/ https://chromium-review.googlesource.com/c/chromium/src/+/4423030 and has been fixed a long time ago. The reason I didn't submit this before is that I have been hitting https://github.com/flathub/im.riot.Riot/issues/381 regardless of whether `--enable-wayland-ime` is added. However https://github.com/flathub/im.riot.Riot/issues/381 doesn't seem to be reproducible w/ 1.11.41 which seems to be using electron26, and `--enable-wayland-ime` works just fine.

Revert "Revert "Enable text-input-v1 support for Wayland IME under KWin/Weston/Hyprland""

---

im.riot.Riot.yaml

This makes the UnityLauncherAPI work. It allows Electron. It allows Element to show the number of unread messages in the Window Icon, on those Desktops that supports it. This is how it looks like on KDE:
It is also supported by [Dash to Dock](https://micheleg.github.io/dash-to-dock/) and [Plank](https://launchpad.net/plank) and most likely also others. Unfortunately Electron [checks if it running on KDE or Unity](https://github.com/electron/electron/blob/fb88375ab4d2161dbf7e958a2a94c7c6d97dc84c/shell/browser/linux/unity_service.cc#L64) before using this API, so we need pretend we are on KDE to make it work on all Desktops.

Make UnityLauncherAPI work

---

im.riot.Riot.metainfo.xml

Picked two colors from https://github.com/element-hq/compound-design-tokens/blob/7f03b365cc6710cde6a02f43db116439eda76321/assets/web/css/cpd-theme-light-base.css#L234 and https://github.com/element-hq/compound-design-tokens/blob/7f03b365cc6710cde6a02f43db116439eda76321/assets/web/css/cpd-theme-dark-base.css#L234
https://docs.flathub.org/banner-preview

Add branding colors

---

README.md
element.sh

Allow user to apply proxy by overriding proxy-related environment variables.
Related issue: #164 
Ref:
> Apparently, you can set the proxy by using a `--proxy-server` option on the command-line (e.g. `--proxy-server=socks5://127.0.0.1:9050`)
_Originally posted by @uhoreg in https://github.com/element-hq/element-desktop/issues/772#issuecomment-1513258947_

feat: enable proxy via reading envrionment variables

---

element.sh

This should resolve potential issues with more exotic distros and their take on wayland support in flatpak.
References:
https://github.com/flathub/im.riot.Riot/pull/494

feat: Evaluate WAYLAND_DISPLAY variable according to spec
